---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: bar-dc2
spec:
  protocol: "http"
---
# Service to expose bar
apiVersion: v1
kind: Service
metadata:
  name: bar-dc2
spec:
  selector:
    app: bar-dc2
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
---
# deployment for bar
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-dc2
  labels:
    app: bar-dc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar-dc2
  template:
    metadata:
      labels:
        app: bar-dc2
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/transparent-proxy": "true"
    spec:
      serviceAccountName: bar-dc2
      containers:
      - name: bar-dc2
        image: nicholasjackson/fake-service:v0.22.4
        ports:
        - containerPort: 9091
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9091"
        - name: "NAME"
          value: "bar-dc2"
        - name: "MESSAGE"
          value: "Response from dc1, should not be visible!!"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bar-dc2
  labels:
    account: bar-dc2
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: bar-dc2
spec:
  connectTimeout: 0s
  redirect:
    service: bar
    datacenter: dc2