---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: bar-dc2
spec:
  protocol: "http"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: bar-dc2
spec:
  connectTimeout: 0s
  redirect:
    service: bar
    datacenter: dc2