# Service to expose cowsay
apiVersion: v1
kind: Service
metadata:
  name: cowsay
spec:
  selector:
    app: cowsay
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cowsay
---
# deployment for cowsay
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay
  labels:
    app: cowsay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowsay
  template:
    metadata:
      labels:
        app: cowsay
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/transparent-proxy": "true"
    spec:
      serviceAccountName: cowsay
      containers:
      - name: cowsay
        image: nicholasjackson/fake-service:v0.22.4
        ports:
        - containerPort: 9091
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9091"
        - name: "NAME"
          value: "cowsay"
        - name: "MESSAGE"
          value: "Response from cowsay-nebula"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: cowsay
spec:
  protocol: "http"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: cowsay
spec:
  connectTimeout: 10s
