apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring: prometheus
  name: vault
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    path: /v1/sys/metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
      #caFile: /etc/prometheus/secrets/vault-tls/ca.crt
      #certFile: /etc/prometheus/secrets/vault-tls/server.crt
      #keyFile: /etc/prometheus/secrets/vault-tls/server.key
  namespaceSelector:
    matchNames:
    - vault
  selector:
    matchLabels:
      app.kubernetes.io/name: vault