apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: details
  ports:
    - protocol: TCP
      name: http
      port: 9080
      targetPort: 9080
    - protocol: TCP
      name: metrics
      port: 20200
      targetPort: 20200
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: details
  labels:
    account: details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "20200"
    spec:
      serviceAccountName: details
      containers:
      - name: details
        image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"