apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: productpage
  ports:
    - protocol: TCP
      name: http
      port: 9090
      targetPort: 9090
    - protocol: TCP
      name: metrics
      port: 20200
      targetPort: 20200
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productpage
  labels:
    account: productpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "20200"
    spec:
      serviceAccountName: productpage
      containers:
      - name: productpage
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
        command: ["python", "productpage.py", "9090"]
        imagePullPolicy: IfNotPresent
        env:
        - name: REVIEWS_HOSTNAME
          value: "reviews.default"
        - name: RATINGS_HOSTNAME
          value: "ratings.default"
        - name: DETAILS_HOSTNAME
          value: "details.default"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
      - name: tmp
        emptyDir: {}