apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: reviews
  namespace: default
spec:
  splits:
    - weight: 0
      serviceSubset: v1
    - weight: 50
      serviceSubset: v2
    - weight: 50
      serviceSubset: v3