---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: ingress-to-productpage
  namespace: default
spec:
  destination:
    name: productpage
    namespace: default
  sources:
    - name: ingress-gateway
      namespace: default
      action: allow