---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  meshGateway:
    mode: local
  config:
    protocol: http
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: backend
spec:
  destination:
    name: backend
  sources:
  - name: frontend
    action: allow
    partition: default
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: eks-red
spec:
  services:
  - name: mesh-gateway
    consumers:
    - partition: default
  - name: backend
    namespace: default
    consumers:
    - partition: default