---
apiVersion: v1
kind: Service
metadata:
  name: bird-backend
  labels:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: bird-backend
  ports:
  - name: http
    protocol: TCP
    port: 7000
    targetPort: 7000
  - name: metrics
    protocol: TCP
    port: 20200
    targetPort: 20200
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bird-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-backend
  labels:
    app: bird-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bird-backend
  template:
    metadata:
      labels:
        app: bird-backend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-version: "v1"
    spec:
      serviceAccountName: bird-backend
      containers:
        - name: bird-backend
          image: ghcr.io/consul-up/birdwatcher-backend:1.0.0
          env:
            - name: BIND_ADDR
              value: "0.0.0.0:7000"
            - name: TRACING_URL
              value: "http://jaeger-collector.default:9411"
          ports:
            - containerPort: 7000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"