---
apiVersion: v1
kind: Service
metadata:
  name: bird-frontend
  labels:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: bird-frontend
  ports:
  - name: http
    protocol: TCP
    port: 6060
    targetPort: 6060
  - name: metrics
    protocol: TCP
    port: 20200
    targetPort: 20200
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bird-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-frontend
  labels:
    app: bird-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bird-frontend
  template:
    metadata:
      labels:
        app: bird-frontend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
    spec:
      serviceAccountName: bird-frontend
      containers:
        - name: bird-frontend
          image: ghcr.io/consul-up/birdwatcher-frontend:1.0.0
          env:
            - name: BIND_ADDR
              value: "0.0.0.0:6060"
            - name: BACKEND_URL
              value: "http://bird-backend"
            - name: TRACING_URL
              value: "http://jaeger-collector.default:9411"
          ports:
            - containerPort: 6060
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"