apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: productpage
          namespace: default
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: ingress-gateway-to-productpage
  namespace: default
spec:
  destination:
    name: productpage
    namespace: default
  sources:
    - name: ingress-gateway
      namespace: default
      action: allow